# Generated by Django 3.0.4 on 2020-09-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('senha', models.CharField(blank=True, max_length=255, null=True, verbose_name='senha')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
