# Generated by Django 3.0.4 on 2020-09-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
