# Generated by Django 3.0.4 on 2020-09-24 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='nome')),
                ('crm', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='telefone')),
                ('status', models.CharField(blank=True, choices=[('ativo', 'ativo'), ('inativo', 'inativo')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='especialidade')),
                ('status', models.CharField(blank=True, choices=[('ativo', 'ativo'), ('inativo', 'inativo')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateField(blank=True, null=True, unique=True, verbose_name='dia')),
                ('status', models.CharField(blank=True, choices=[('ativo', 'ativo'), ('inativo', 'inativo')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Doctor', verbose_name='médico')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(blank=True, null=True, to='schedules.Specialty', verbose_name='especialidades'),
        ),
        migrations.CreateModel(
            name='AvailableTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(blank=True, verbose_name='horário')),
                ('status', models.CharField(blank=True, choices=[('ativo', 'ativo'), ('inativo', 'inativo')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
            },
        ),
    ]
