# Generated by Django 3.0.4 on 2020-09-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletimes',
            name='hour',
            field=models.TimeField(blank=True, error_messages={'unique': 'My custom message'}, verbose_name='horário'),
        ),
    ]
