# Generated by Django 3.0.4 on 2020-09-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20200923_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletimes',
            name='hour',
            field=models.TimeField(blank=True, error_messages={'unique': 'Este horário já foi registrado para esta data.'}, unique=True, verbose_name='horário'),
        ),
    ]
