# Generated by Django 3.0.4 on 2020-09-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20200923_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.DateField(blank=True, error_messages={'unique': 'Este data já foi registrada para este médico.'}, null=True, unique=True, verbose_name='dia'),
        ),
    ]
