# Generated by Django 3.0.4 on 2020-09-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20200923_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletimes',
            name='hour',
            field=models.TimeField(blank=True, verbose_name='horário'),
        ),
        migrations.AlterUniqueTogether(
            name='availabletimes',
            unique_together={('schedule', 'hour')},
        ),
    ]
