# Generated by Django 2.2.1 on 2020-09-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20200923_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule',
            new_name='day',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'day')},
        ),
    ]
