# Generated by Django 2.2.1 on 2020-09-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_account'),
        ('schedules', '0010_auto_20200924_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(blank=True, verbose_name='horário')),
                ('status', models.CharField(blank=True, choices=[('ativo', 'ativo'), ('inativo', 'inativo')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule', verbose_name='agenda')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Account', verbose_name='usuário')),
            ],
        ),
    ]
