# Generated by Django 2.2.1 on 2020-09-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
    ]
