# Generated by Django 2.2.1 on 2020-09-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_auto_20200924_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
