# Generated by Django 2.2.1 on 2020-09-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_auto_20200924_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(error_messages={'unique_together': ''}, null=True, verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Doctor', verbose_name='médico'),
        ),
    ]
